In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([[1,2,3,4,5]])) # [[ means two dimension ]]

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,"jalpa", 6+6j])

array(['1', '2', '3', '4', '5', 'jalpa', '(6+6j)'], dtype='<U64')

In [7]:
np.array([[1,4],[4,5]])

array([[1, 4],
       [4, 5]])

In [10]:
np.array([[1,4], [4,5],[6,7]])

array([[1, 4],
       [4, 5],
       [6, 7]])

In [11]:
np.array([1,2,3], ndmin =2)

array([[1, 2, 3]])

In [13]:
type(np.array([1,2,3],ndmin = 3))

numpy.ndarray

In [14]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array([1,2,3], dtype = int)

array([1, 2, 3])

In [16]:
arr=np.array([(1,2), (3,4)])

In [17]:
arr

array([[1, 2],
       [3, 4]])

In [18]:
arr[0][0]

1

In [19]:
arr[0][0] = 800

In [20]:
arr

array([[800,   2],
       [  3,   4]])

In [21]:
np.mat(arr) # mat means matrix

matrix([[800,   2],
        [  3,   4]])

In [22]:
l = [3,4,5,6,7]

In [23]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [24]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [25]:
np.array(l)

array([3, 4, 5, 6, 7])

In [27]:
np.fromfunction(lambda i, j:i==j, (4,4)) # from lambda function

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [28]:
np.fromfunction(lambda i, j:i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
np.fromfunction(lambda i,j: i/j, (3,3))

C:\Users\Jaimin Shah\AppData\Local\Temp\ipykernel_25412\2105401307.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j: i/j, (3,3))
C:\Users\Jaimin Shah\AppData\Local\Temp\ipykernel_25412\2105401307.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j: i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [31]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

In [32]:
np.fromstring('1,2,3', sep =',', dtype = int)

array([1, 2, 3])

In [33]:
np.fromstring('1:2:3:5', sep = ':', dtype = int)

array([1, 2, 3, 5])

In [34]:
np.fromstring('1;2', sep = ';', dtype = complex)

array([1.+0.j, 2.+0.j])

In [35]:
np.fromstring('1,2,3,4', sep = ',')

array([1., 2., 3., 4.])

In [36]:
l = [[1,2,3,4], [1,3,4,5], [5,6,7,8], [5,6,7,8]] # 2 dimension

In [37]:
arr=np.array(l)

In [38]:
arr

array([[1, 2, 3, 4],
       [1, 3, 4, 5],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [39]:
arr.ndim

2

In [40]:
type(arr)

numpy.ndarray

In [41]:
arr.size

16

In [42]:
arr.shape

(4, 4)

In [43]:
arr.dtype

dtype('int32')

In [46]:
list(range(1,6))

[1, 2, 3, 4, 5]

In [47]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [49]:
np.arange(6.6,8,0.2)

array([6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ])

In [51]:
np.linspace(3,8) # generates random numbers

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [52]:
np.linspace(1,2,6) # divides in 6 partitions

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,5)) # 2 - number of rows, 5 - number of columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros((3,5,4))+5 # 3 - number of matrix, 5 - number of rows, 4 - number of columns

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3,2))+3

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [11]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.eye(3) # eye means diagonal 1 and rest are zeros

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np. linspace(2,4,4, endpoint =False, axis=0) # axis0 = number of rows, axis1 = number of columns

array([2. , 2.5, 3. , 3.5])

In [14]:
np. linspace(2,4,4, endpoint =True, axis=0)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [15]:
np.logspace(1.0,4.0, num=4)

array([   10.,   100.,  1000., 10000.])

In [16]:
import numpy as np
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [17]:
d = np.linspace(4,5,40)

In [18]:
d

array([4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
       4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
       4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
       4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949,
       4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
       4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
       4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
       4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ])

In [19]:
d.shape

(40,)

In [20]:
d.reshape(10,4)

array([[4.        , 4.02564103, 4.05128205, 4.07692308],
       [4.1025641 , 4.12820513, 4.15384615, 4.17948718],
       [4.20512821, 4.23076923, 4.25641026, 4.28205128],
       [4.30769231, 4.33333333, 4.35897436, 4.38461538],
       [4.41025641, 4.43589744, 4.46153846, 4.48717949],
       [4.51282051, 4.53846154, 4.56410256, 4.58974359],
       [4.61538462, 4.64102564, 4.66666667, 4.69230769],
       [4.71794872, 4.74358974, 4.76923077, 4.79487179],
       [4.82051282, 4.84615385, 4.87179487, 4.8974359 ],
       [4.92307692, 4.94871795, 4.97435897, 5.        ]])

In [21]:
d.reshape(1,2,20)

array([[[4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
         4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
         4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
         4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949],
        [4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
         4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
         4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
         4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ]]])

In [22]:
d.reshape(2,1,20)

array([[[4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
         4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
         4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
         4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949]],

       [[4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
         4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
         4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
         4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ]]])

In [23]:
np.random.rand(10) # rand means generates random numbers from 0 to 1

array([0.17162774, 0.50193814, 0.85110576, 0.34421457, 0.48631097,
       0.91916016, 0.5171468 , 0.53651495, 0.91806246, 0.85909595])

In [24]:
np.random.rand(5,5)

array([[0.07972939, 0.9571898 , 0.36640674, 0.45692266, 0.16735479],
       [0.95466788, 0.72156122, 0.65201418, 0.3760649 , 0.24238379],
       [0.91295416, 0.42556407, 0.48988995, 0.77302445, 0.88005067],
       [0.71296578, 0.36084423, 0.84075072, 0.50581339, 0.79735951],
       [0.91732893, 0.32161102, 0.6205272 , 0.83022186, 0.50109733]])

In [25]:
np.random.rand(2,2,3) # 2 - rows, 2 - columns, 3 - matrix

array([[[0.65335064, 0.90228312, 0.38271725],
        [0.01883892, 0.69705906, 0.24330842]],

       [[0.22654512, 0.67467124, 0.8876213 ],
        [0.85616727, 0.91232144, 0.58191411]]])

In [29]:
np.random.randint(6) # generates randint from 0 to 6

3

In [36]:
np.random.randint((4,7),40) # generates numbers within 40 but more than 4 and 7

array([23, 17])

In [31]:
np.random.randint(5,9,10) # generates random numbers from 5 to 9 and with 10 numbers

array([5, 7, 6, 7, 5, 8, 5, 6, 6, 6])

In [38]:
np.random.randn(4,4) # randn means negative and positive numbers

array([[-0.08942708, -1.02644106,  0.73565412,  0.4825481 ],
       [ 0.16991127, -0.26950745, -1.57076805, -0.31197766],
       [ 0.84791837, -0.70241611,  0.16626014, -0.1838801 ],
       [ 1.71146875,  0.1479261 , -0.05568492,  0.49953526]])

In [39]:
arr = np.random.randint(3,9,(3,3))

In [40]:
arr

array([[7, 5, 8],
       [8, 5, 8],
       [5, 6, 3]])

In [41]:
arr.reshape(1,1,9)

array([[[7, 5, 8, 8, 5, 8, 5, 6, 3]]])

In [42]:
arr.reshape(3,3,1) # 3 - matrix, 3 - rows, 1 - column

array([[[7],
        [5],
        [8]],

       [[8],
        [5],
        [8]],

       [[5],
        [6],
        [3]]])

In [43]:
arr.reshape(3,-2) # negative value doesnt change matrix

array([[7, 5, 8],
       [8, 5, 8],
       [5, 6, 3]])

In [44]:
arr.reshape(3,-9898)

array([[7, 5, 8],
       [8, 5, 8],
       [5, 6, 3]])

In [45]:
arr.max()

8

In [46]:
arr.min()

3

In [47]:
arr = np.random.randint(4,100,(5,5))

In [49]:
arr

array([[47, 49, 79, 38, 69],
       [75, 38, 99, 48,  9],
       [36, 32, 29, 44, 50],
       [59, 32, 64, 34, 90],
       [17, 15, 59, 15, 52]])

In [50]:
arr[2:,2:]

array([[29, 44, 50],
       [64, 34, 90],
       [59, 15, 52]])

In [51]:
arr[1:4,1:4]

array([[38, 99, 48],
       [32, 29, 44],
       [32, 64, 34]])

In [55]:
arr[1:3:4,1:]

array([[38, 99, 48,  9]])

In [58]:
arr[:,[1,3]] # : means all rows, 1,3 after 1 column and after 3 column

array([[49, 38],
       [38, 48],
       [32, 44],
       [32, 34],
       [15, 15]])

In [59]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [60]:
arr[arr>10]

array([47, 49, 79, 38, 69, 75, 38, 99, 48, 36, 32, 29, 44, 50, 59, 32, 64,
       34, 90, 17, 15, 59, 15, 52])

In [1]:
# Pandas - Pandas is an open source, BSD-licensed ibrary providng high-performace, easy to use data structures and data analysis
# tools for the Python Programming Language
# What is Data Frames?
# What is Data Series?
# Different operations in Pandas

In [4]:
# First step is to import pandas and numpy
import pandas as pd
import numpy as np

In [5]:
df1 = (np.arange(0,100).reshape(10,10))
df1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
type(df1)

numpy.ndarray

In [7]:
df=pd.DataFrame(df1)
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
# Playing with DataFrame
df=pd.DataFrame(df1, index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5', 'Row6', 'Row7', 'Row8', 'Row9', 'Row10'],
                columns = ['Column1', 'Column2', 'Column3', 'column4', 'column5', 'column6', 'column7', 'column8',
                          'column9', 'column10'])

In [10]:
df

Column1  Column2  Column3  column4  column5  column6  column7  column8  \
Row1         0        1        2        3        4        5        6        7   
Row2        10       11       12       13       14       15       16       17   
Row3        20       21       22       23       24       25       26       27   
Row4        30       31       32       33       34       35       36       37   
Row5        40       41       42       43       44       45       46       47   
Row6        50       51       52       53       54       55       56       57   
Row7        60       61       62       63       64       65       66       67   
Row8        70       71       72       73       74       75       76       77   
Row9        80       81       82       83       84       85       86       87   
Row10       90       91       92       93       94       95       96       97   

       column9  column10  
Row1         8         9  
Row2        18        19  
Row3        28        29  
Row4        38        39  
Row5        48        49  
Row6        58        59  
Row7        68        69  
Row8        78        79  
Row9        88        89  
Row10       98        99

In [11]:
df.head() # by default gives first 5 rows value

Column1  Column2  Column3  column4  column5  column6  column7  column8  \
Row1        0        1        2        3        4        5        6        7   
Row2       10       11       12       13       14       15       16       17   
Row3       20       21       22       23       24       25       26       27   
Row4       30       31       32       33       34       35       36       37   
Row5       40       41       42       43       44       45       46       47   

      column9  column10  
Row1        8         9  
Row2       18        19  
Row3       28        29  
Row4       38        39  
Row5       48        49

In [12]:
df.head(2)

Column1  Column2  Column3  column4  column5  column6  column7  column8  \
Row1        0        1        2        3        4        5        6        7   
Row2       10       11       12       13       14       15       16       17   

      column9  column10  
Row1        8         9  
Row2       18        19

In [13]:
df.tail() # by default gives last 5 rows values

Column1  Column2  Column3  column4  column5  column6  column7  column8  \
Row6        50       51       52       53       54       55       56       57   
Row7        60       61       62       63       64       65       66       67   
Row8        70       71       72       73       74       75       76       77   
Row9        80       81       82       83       84       85       86       87   
Row10       90       91       92       93       94       95       96       97   

       column9  column10  
Row6        58        59  
Row7        68        69  
Row8        78        79  
Row9        88        89  
Row10       98        99

In [14]:
df.tail(2)

Column1  Column2  Column3  column4  column5  column6  column7  column8  \
Row9        80       81       82       83       84       85       86       87   
Row10       90       91       92       93       94       95       96       97   

       column9  column10  
Row9        88        89  
Row10       98        99

In [15]:
df['Column2'] # gives column2 values

Row1      1
Row2     11
Row3     21
Row4     31
Row5     41
Row6     51
Row7     61
Row8     71
Row9     81
Row10    91
Name: Column2, dtype: int32

In [16]:
df.shape

(10, 10)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Row1 to Row10
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column1   10 non-null     int32
 1   Column2   10 non-null     int32
 2   Column3   10 non-null     int32
 3   column4   10 non-null     int32
 4   column5   10 non-null     int32
 5   column6   10 non-null     int32
 6   column7   10 non-null     int32
 7   column8   10 non-null     int32
 8   column9   10 non-null     int32
 9   column10  10 non-null     int32
dtypes: int32(10)
memory usage: 780.0+ bytes


In [18]:
df.dtypes # gives data type for values

Column1     int32
Column2     int32
Column3     int32
column4     int32
column5     int32
column6     int32
column7     int32
column8     int32
column9     int32
column10    int32
dtype: object

In [19]:
# accessing the elements
df.loc['Row2']

Column1     10
Column2     11
Column3     12
column4     13
column5     14
column6     15
column7     16
column8     17
column9     18
column10    19
Name: Row2, dtype: int32

In [20]:
# check the type
type(df.loc['Row2'])

pandas.core.series.Series

In [21]:
df.iloc[3:7,3:6]

column4  column5  column6
Row4       33       34       35
Row5       43       44       45
Row6       53       54       55
Row7       63       64       65

In [22]:
# convert DataFrames into array 
# .values converts dataframe into array
df.iloc[:,1:].values

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
type(df.iloc[:,1:].values)

numpy.ndarray

In [24]:
df.describe() # very very important - 5 number summary in statistics

Column1    Column2    Column3    column4    column5    column6  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

         column7    column8    column9   column10  
count  10.000000  10.000000  10.000000  10.000000  
mean   51.000000  52.000000  53.000000  54.000000  
std    30.276504  30.276504  30.276504  30.276504  
min     6.000000   7.000000   8.000000   9.000000  
25%    28.500000  29.500000  30.500000  31.500000  
50%    51.000000  52.000000  53.000000  54.000000  
75%    73.500000  74.500000  75.500000  76.500000  
max    96.000000  97.000000  98.000000  99.000000

In [25]:
df.isnull().sum() # No null values present

Column1     0
Column2     0
Column3     0
column4     0
column5     0
column6     0
column7     0
column8     0
column9     0
column10    0
dtype: int64

In [26]:
df['Column1']

Row1      0
Row2     10
Row3     20
Row4     30
Row5     40
Row6     50
Row7     60
Row8     70
Row9     80
Row10    90
Name: Column1, dtype: int32

In [27]:
df['Column1'].value_counts() # counts number of repeated values 

Column1
0     1
10    1
20    1
30    1
40    1
50    1
60    1
70    1
80    1
90    1
Name: count, dtype: int64

In [28]:
df.isnull().sum()

Column1     0
Column2     0
Column3     0
column4     0
column5     0
column6     0
column7     0
column8     0
column9     0
column10    0
dtype: int64

In [29]:
df.duplicated().sum() # finds duplicate values

0

In [30]:
df.drop('Column1', axis=1)

Column2  Column3  column4  column5  column6  column7  column8  column9  \
Row1         1        2        3        4        5        6        7        8   
Row2        11       12       13       14       15       16       17       18   
Row3        21       22       23       24       25       26       27       28   
Row4        31       32       33       34       35       36       37       38   
Row5        41       42       43       44       45       46       47       48   
Row6        51       52       53       54       55       56       57       58   
Row7        61       62       63       64       65       66       67       68   
Row8        71       72       73       74       75       76       77       78   
Row9        81       82       83       84       85       86       87       88   
Row10       91       92       93       94       95       96       97       98   

       column10  
Row1          9  
Row2         19  
Row3         29  
Row4         39  
Row5         49  
Row6         59  
Row7         69  
Row8         79  
Row9         89  
Row10        99

In [31]:
df.head()

Column1  Column2  Column3  column4  column5  column6  column7  column8  \
Row1        0        1        2        3        4        5        6        7   
Row2       10       11       12       13       14       15       16       17   
Row3       20       21       22       23       24       25       26       27   
Row4       30       31       32       33       34       35       36       37   
Row5       40       41       42       43       44       45       46       47   

      column9  column10  
Row1        8         9  
Row2       18        19  
Row3       28        29  
Row4       38        39  
Row5       48        49

In [37]:
df.drop('Column2',axis=1,inplace=True)
df

Column3  column4  column5  column6  column7  column8  column9  column10
Row1         2        3        4        5        6        7        8         9
Row2        12       13       14       15       16       17       18        19
Row3        22       23       24       25       26       27       28        29
Row4        32       33       34       35       36       37       38        39
Row5        42       43       44       45       46       47       48        49
Row6        52       53       54       55       56       57       58        59
Row7        62       63       64       65       66       67       68        69
Row8        72       73       74       75       76       77       78        79
Row9        82       83       84       85       86       87       88        89
Row10       92       93       94       95       96       97       98        99

In [33]:
df.head()

Column2  Column3  column4  column5  column6  column7  column8  column9  \
Row1        1        2        3        4        5        6        7        8   
Row2       11       12       13       14       15       16       17       18   
Row3       21       22       23       24       25       26       27       28   
Row4       31       32       33       34       35       36       37       38   
Row5       41       42       43       44       45       46       47       48   

      column10  
Row1         9  
Row2        19  
Row3        29  
Row4        39  
Row5        49

In [34]:
df.drop_duplicates()

Column2  Column3  column4  column5  column6  column7  column8  column9  \
Row1         1        2        3        4        5        6        7        8   
Row2        11       12       13       14       15       16       17       18   
Row3        21       22       23       24       25       26       27       28   
Row4        31       32       33       34       35       36       37       38   
Row5        41       42       43       44       45       46       47       48   
Row6        51       52       53       54       55       56       57       58   
Row7        61       62       63       64       65       66       67       68   
Row8        71       72       73       74       75       76       77       78   
Row9        81       82       83       84       85       86       87       88   
Row10       91       92       93       94       95       96       97       98   

       column10  
Row1          9  
Row2         19  
Row3         29  
Row4         39  
Row5         49  
Row6         59  
Row7         69  
Row8         79  
Row9         89  
Row10        99

In [44]:
df.drop_duplicates(keep='last')

Column2  Column3  column4  column5  column6  column7  column8  column9  \
Row1         1        2        3        4        5        6        7        8   
Row2        11       12       13       14       15       16       17       18   
Row3        21       22       23       24       25       26       27       28   
Row4        31       32       33       34       35       36       37       38   
Row5        41       42       43       44       45       46       47       48   
Row6        51       52       53       54       55       56       57       58   
Row7        61       62       63       64       65       66       67       68   
Row8        71       72       73       74       75       76       77       78   
Row9        81       82       83       84       85       86       87       88   
Row10       91       92       93       94       95       96       97       98   

       column10  
Row1          9  
Row2         19  
Row3         29  
Row4         39  
Row5         49  
Row6         59  
Row7         69  
Row8         79  
Row9         89  
Row10        99

In [45]:
df[df['Column2']>50] # values greater than 50

Column2  Column3  column4  column5  column6  column7  column8  column9  \
Row6        51       52       53       54       55       56       57       58   
Row7        61       62       63       64       65       66       67       68   
Row8        71       72       73       74       75       76       77       78   
Row9        81       82       83       84       85       86       87       88   
Row10       91       92       93       94       95       96       97       98   

       column10  
Row6         59  
Row7         69  
Row8         79  
Row9         89  
Row10        99

In [46]:
df.corr() # correlation values from -1 to 1

Column2  Column3  column4  column5  column6  column7  column8  \
Column2       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
Column3       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
column4       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
column5       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
column6       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
column7       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
column8       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
column9       1.0      1.0      1.0      1.0      1.0      1.0      1.0   
column10      1.0      1.0      1.0      1.0      1.0      1.0      1.0   

          column9  column10  
Column2       1.0       1.0  
Column3       1.0       1.0  
column4       1.0       1.0  
column5       1.0       1.0  
column6       1.0       1.0  
column7       1.0       1.0  
column8       1.0       1.0  
column9       1.0       1.0  
column10      1.0       1.0

In [47]:
import numpy as np
import pandas as pd

In [49]:
data = [[1,2,3,4,44], [3,4,5,6,65],[5,6,np.nan,7,8], [np.nan, np.nan, 89,99]]
data

[[1, 2, 3, 4, 44], [3, 4, 5, 6, 65], [5, 6, nan, 7, 8], [nan, nan, 89, 99]]

In [50]:
df=pd.DataFrame(data)
df

0    1     2   3     4
0  1.0  2.0   3.0   4  44.0
1  3.0  4.0   5.0   6  65.0
2  5.0  6.0   NaN   7   8.0
3  NaN  NaN  89.0  99   NaN

In [51]:
df.isnull().sum()

0    1
1    1
2    1
3    0
4    1
dtype: int64

In [52]:
df.dropna() # drops all null values in rows and columns

0    1    2  3     4
0  1.0  2.0  3.0  4  44.0
1  3.0  4.0  5.0  6  65.0

In [53]:
df

0    1     2   3     4
0  1.0  2.0   3.0   4  44.0
1  3.0  4.0   5.0   6  65.0
2  5.0  6.0   NaN   7   8.0
3  NaN  NaN  89.0  99   NaN

In [55]:
# Handling  Missing Values
# Drop nan values
df.dropna(axis=0,inplace=True)
df

0    1    2  3     4
0  1.0  2.0  3.0  4  44.0
1  3.0  4.0  5.0  6  65.0